let username = "Kirill"
let nameOfTheCity = "Minsk"
let yearOfBirth = 2003
let redColor = "Red"
let usersAnswer = prompt("Да или нет?", '')
let infinity = Infinity
let number = 532
let perimeter = "120mm"
let message = alert("Введенные данные неверны")